/**
 * 一键转化为新书项目 (仿写脚手架) 弹窗
 */

import { Dialog, Button, Flex, Text, TextField, TextArea, Box, Badge } from "@radix-ui/themes";
import { BookPlus, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";

interface CreateProjectDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  defaultTitle: string;
  defaultDescription: string;
  loading: boolean;
  onSubmit: (title: string, description: string) => void;
}

export function CreateProjectDialog({
  open,
  onOpenChange,
  defaultTitle,
  defaultDescription,
  loading,
  onSubmit,
}: CreateProjectDialogProps) {
  const { t } = useTranslation();
  const [title, setTitle] = useState(defaultTitle);
  const [description, setDescription] = useState(defaultDescription);

  useEffect(() => {
    if (open) {
      setTitle(defaultTitle);
      setDescription(defaultDescription);
    }
  }, [open, defaultTitle, defaultDescription]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim()) return;
    onSubmit(title.trim(), description.trim());
  };

  return (
    <Dialog.Root open={open} onOpenChange={onOpenChange}>
      <Dialog.Content maxWidth="520px">
        <Dialog.Title>
          <Flex align="center" gap="2">
            <BookPlus size={20} color="var(--accent-9)" />
            <Text>{t("deconstruction.createProjectTitle", "转化为新书项目 (仿写脚手架)")}</Text>
          </Flex>
        </Dialog.Title>
        <Dialog.Description size="2" color="gray" mb="4">
          {t(
            "deconstruction.createProjectDesc",
            "系统将根据拆书分析报告，自动为您创建新书并预置世界观、角色卡片与章节大纲，直接提笔开始仿写创作。",
          )}
        </Dialog.Description>

        <form onSubmit={handleSubmit}>
          <Flex direction="column" gap="4">
            <Box>
              <Text as="label" size="2" weight="medium" mb="1" style={{ display: "block" }}>
                {t("deconstruction.projectTitleLabel", "新小说书名")}
              </Text>
              <TextField.Root
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                placeholder={t("deconstruction.projectTitlePlaceholder", "例如：《新世界之王》")}
                required
                disabled={loading}
              />
            </Box>

            <Box>
              <Text as="label" size="2" weight="medium" mb="1" style={{ display: "block" }}>
                {t("deconstruction.projectDescLabel", "新书简介 / 故事核心框架")}
              </Text>
              <TextArea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder={t("deconstruction.projectDescPlaceholder", "核心故事框架与爽点卖点...")}
                rows={4}
                disabled={loading}
              />
            </Box>

            <Box p="3" style={{ background: "var(--gray-a2)", borderRadius: "var(--radius-3)" }}>
              <Flex direction="column" gap="2">
                <Flex align="center" gap="1">
                  <Sparkles size={14} color="var(--accent-9)" />
                  <Text size="2" weight="medium">
                    {t("deconstruction.autoGeneratedAssets", "将自动为您生成的资产：")}
                  </Text>
                </Flex>
                <Flex wrap="wrap" gap="2">
                  <Badge color="blue" variant="soft">
                    {t("deconstruction.assetWorldView", "世界观规则设定")}
                  </Badge>
                  <Badge color="green" variant="soft">
                    {t("deconstruction.assetCharacters", "男/女主角人物档案")}
                  </Badge>
                  <Badge color="purple" variant="soft">
                    {t("deconstruction.assetOutline", "分卷与各章节大纲草稿")}
                  </Badge>
                  <Badge color="amber" variant="soft">
                    {t("deconstruction.assetNote", "全篇拆书对照参考笔记")}
                  </Badge>
                </Flex>
              </Flex>
            </Box>

            <Flex justify="end" gap="3" mt="2">
              <Dialog.Close>
                <Button variant="soft" color="gray" type="button" disabled={loading}>
                  {t("common.cancel", "取消")}
                </Button>
              </Dialog.Close>
              <Button type="submit" loading={loading} disabled={!title.trim() || loading}>
                {t("deconstruction.confirmCreateBtn", "立即生成并开启创作")}
              </Button>
            </Flex>
          </Flex>
        </form>
      </Dialog.Content>
    </Dialog.Root>
  );
}
